### ISSUE TITLE
Error: Running without the SUID sandbox

### ISSUE THREAD

**Issue by mmatyas** [Sytten/Facebook-Messenger-Desktop#23]
After having SSL problems on Ubuntu 14.04 with the official version, like [this](https://github.com/Aluxian/Facebook-Messenger-Desktop/issues/374#issuecomment-198135928), I've wanted to try your fork. However, v1.4.7 from the Releases gives this error, and does not load any content:

```
[20788:0319/154227:ERROR:browser_main_loop.cc(170)] Running without the SUID sandbox! See https://code.google.com/p/chromium/wiki/LinuxSUIDSandboxDevelopment for more information on developing with the sandbox on.
```

**Comment by Sytten** [comment]
Ubuntu 14.04 seems to have some trouble... I currently dont have the time to fix it, but maybe you can try readding the app in the sandbox. I think he disabled it somewhere in the code/config files

**Comment by nevercast** [comment]
Messenger.com uses ECC for it's certificates It's possible (however unlikely) that the system is not updated to support it. How up to date is your distro, @mmatyas ?

**Comment by mmatyas** [comment]
This problem happens for me on Ubuntu 14.04, with all the available updates installed.
On 15.10, the app works fine.

**Comment by nevercast** [comment]
The sandbox error is a non-error. The security warning was removed in nwjs 0.13beta. https://github.com/nwjs/nw.js/issues/2699#issuecomment-192650852

Closing because this issue is not related to the actual issue. I believe the solution to be here: https://github.com/Aluxian/Facebook-Messenger-Desktop/issues/374

Please leave further comments regarding MFD not working on Ubuntu, there.
Regards, Josh.
