### ISSUE TITLE
build OSX releases

### ISSUE THREAD

**Issue by terinjokes** [Sytten/Facebook-Messenger-Desktop#3]
Hey Émile, I like some of the changes you've made to Messenger.app.

I'm assuming you're not on OS X by the lack of an OS X release. Would you like me to build and sign them?

**Comment by Sytten** [comment]
Yes, if you can do it that would be nice!

**Comment by Sytten** [comment]
I know there are still some bugs on mac (platform specific things), but I can't correct them properly since I can't test the app

**Comment by terinjokes** [comment]
> I know there are still some bugs on mac (platform specific things)

No worries, I'm able to take a look at some things.

A dmg for 1.4.6 is ready, it's uploading to somewhere where you can download (since it's larger than GitHub's 10MB limit)

**Comment by terinjokes** [comment]
https://share.terinstock.com/Messenger_v1.4.6.dmg

The updater looks for "Messenger.dmg" on the release (of course, the updater in <1.4.6 is broken, so…).

**Comment by Sytten** [comment]
Good I will add it to the release and change the website. I will change the build script for further releases to have the version in the name.

EDIT: Done

**Comment by Sytten** [comment]
@terinjokes Hey! Can you do me a new dmg today? I will release a new version later today

**Comment by vallovic** [comment]
Hi! Since I'm a user of the Linux app version at work and the Mac app version at home, and given the fact that the most recent version wasn't already packed for Mac, I've just did it.

I packed it and tested and everything seems to work five, couldn't detect anything broken. If you want to use it, just feel free to download it here, courtesy of WeTransfer: http://we.tl/Lt1TJTRPSW

**Comment by Sytten** [comment]
Thanks!

**Comment by Sytten** [comment]
I know have a hackintosh so I can build them!
